name: Build and Deploy .NET App with EF Core Migrations

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' 

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Install EF Core CLI
        run: dotnet tool install --global dotnet-ef

      - name: Update database
        env:
          ConnectionStrings__DefaultConnection: ${{ secrets.POSTGRES_CONNECTION }}
        run: |
          dotnet ef database update --project ./LmsApi.csproj \
            --connection "$ConnectionStrings__DefaultConnection"

      - name: Publish project
        run: dotnet publish ./LmsApi.csproj -c Release -o ./publish
